s3_region: s3://eu-west-1
bucketnames: gs-loki-storage
podAnnotations:
  iam.amazonaws.com/role: loki-s3-access

global:
  dnsService: "coredns"

gateway:
  replicas: 3
  ingress:
    enabled: true
    hosts:
      - host: loki.m2h60.k8s.gauss.eu-west-1.aws.gigantic.io
        paths:
          - /
    tls:
      - hosts:
          - loki.m2h60.k8s.gauss.eu-west-1.aws.gigantic.io
        secretName: loki-ingress-cert

s3_annotations: &s3-ann
  podAnnotations:
    iam.amazonaws.com/role: loki-s3-access

ingester: *s3-ann

distributor: *s3-ann

querier: *s3-ann

queryFrontend: *s3-ann
